// src/components/seo.tsx
import * as React from "react";
import { Helmet } from "react-helmet";
import { useStaticQuery, graphql } from "gatsby";

interface Props {
    description?: string;
    lang?: string;
    meta?: { name?: string; property?: string; content: string }[];
    title?: string;
    image?: string;
}

const Seo: React.FC<Props> = ({
    description = "",
    lang = "en",
    meta = [],
    title = "jordanrhea.com",
    image,
}) => {
    const { site } = useStaticQuery(
        graphql`
            query {
                site {
                    siteMetadata {
                        title
                        description
                        siteUrl
                        social {
                            twitter
                        }
                    }
                }
            }
        `
    );

    const metaDescription = description || site.siteMetadata.description;
    const defaultTitle = site.siteMetadata?.title;

    if (image) {
        const content = image;
        // const content = site.siteMetadata.siteUrl + image;
        meta = [
            ...meta,
            {
                property: `og:image`,
                content,
            },
            {
                name: `twitter:image`,
                content,
            },
        ];
    }

    return (
        <Helmet
            htmlAttributes={{
                lang,
            }}
            title={title}
            titleTemplate={defaultTitle ? `%s | ${defaultTitle}` : undefined}
            meta={[
                {
                    name: `description`,
                    content: metaDescription,
                },
                {
                    property: `og:title`,
                    content: title,
                },
                {
                    property: `og:description`,
                    content: metaDescription,
                },
                {
                    property: `og:type`,
                    content: `website`,
                },
                {
                    name: `twitter:card`,
                    content: `summary`,
                },
                {
                    name: `twitter:creator`,
                    content: site.siteMetadata?.social?.twitter || ``,
                },
                {
                    name: `twitter:title`,
                    content: title,
                },
                {
                    name: `twitter:description`,
                    content: metaDescription,
                },
                ...meta,
            ]}
        />
    );
};

export default Seo;

// src/components/solid/seo.tsx
import { Title, Meta } from "@solidjs/meta";
import { Show, For } from "solid-js";
import { siteMetadata } from "../../site-config";

interface SeoProps {
  description?: string;
  lang?: string;
  meta?: { name?: string; property?: string; content: string }[];
  title?: string;
  image?: string;
}

export default function Seo(props: SeoProps) {
  const description = () => props.description || siteMetadata.description;
  const title = () => props.title || "jordanrhea.com";
  const defaultTitle = siteMetadata.title;
  const fullTitle = () => defaultTitle ? `${title()} | ${defaultTitle}` : title();

  return (
    <>
      <Title>{fullTitle()}</Title>
      <Meta name="description" content={description()} />
      <Meta property="og:title" content={title()} />
      <Meta property="og:description" content={description()} />
      <Meta property="og:type" content="website" />
      <Meta name="twitter:card" content="summary" />
      <Meta name="twitter:creator" content={siteMetadata.social?.twitter || ""} />
      <Meta name="twitter:title" content={title()} />
      <Meta name="twitter:description" content={description()} />
      <Show when={props.image}>
        <Meta property="og:image" content={props.image!} />
        <Meta name="twitter:image" content={props.image!} />
      </Show>
      <For each={props.meta || []}>
        {(m) => (
          <Show when={m.name || m.property}>
            <Meta {...(m.name ? { name: m.name } : {})} {...(m.property ? { property: m.property } : {})} content={m.content} />
          </Show>
        )}
      </For>
    </>
  );
}
