// src/components/twitter-subscribe.tsx
import React from "react";
import { Helmet } from "react-helmet";

export const TwitterSubscribe: React.FC = () => {
    return (
        <>
            <Helmet>
                <script
                    async
                    src="https://platform.twitter.com/widgets.js"
                    charSet="utf-8"
                ></script>
            </Helmet>
            <a
                href="https://twitter.com/rheajt?ref_src=twsrc%5Etfw"
                className="twitter-follow-button"
                data-size="large"
                data-show-count="false"
            >
                Follow @rheajt
            </a>
        </>
    );
};

// src/components/solid/twitter-subscribe.tsx
import { onMount } from "solid-js";

const TwitterSubscribe = (props: { username: string }) => {
  onMount(() => {
    const script = document.createElement("script");
    script.src = "https://platform.twitter.com/widgets.js";
    script.async = true;
    document.head.appendChild(script);
  });
  return <a href={`https://twitter.com/${props.username}`} class="twitter-follow-button" data-show-count="false">Follow @{props.username}</a>;
};

export default TwitterSubscribe;
