// src/components/solid/youtube-subscribe.tsx
import { onMount } from "solid-js";

const YoutubeSubscribe = (props: { channelId: string }) => {
  onMount(() => {
    const script = document.createElement("script");
    script.src = "https://apis.google.com/js/platform.js";
    script.async = true;
    document.head.appendChild(script);
  });
  return <div class="g-ytsubscribe" data-channelid={props.channelId} data-layout="default" data-count="default"></div>;
};

export default YoutubeSubscribe;

// src/components/youtube-subscribe.tsx
import React, { useRef } from "react";
import { Helmet } from "react-helmet";

interface Props {
    channelId: string;
    layout: string;
    count: string;
}
const YoutubeSubscribe: React.FC<Props> = ({ channelId, layout, count }) => {
    const subBtn = useRef<HTMLDivElement>(null);

    return (
        <>
            <Helmet>
                <script src="https://apis.google.com/js/platform.js"></script>
            </Helmet>

            <div
                ref={subBtn}
                className="g-ytsubscribe"
                data-channelid={channelId}
                data-layout={layout}
                data-count={count}
            />
        </>
    );
};

export default YoutubeSubscribe;
